.TH E 1 e\-VERSION
.SH NAME
E \- A text editor my way
.SH DESCRIPTION
This document contains my notes and thoughts while developing E including it's theory of operation
.SH OPERATING ENVIRONMENT
E is a VT10X compatible terminal application built in C.  It requires a C99 compliant libc and a VT10X compliant terminal.
.SH GOALS

\- Modal editing similar to vim (inset/command/visual)

\- Entirely keymapped (including the ability to execute arbitrary shell commands i.e. run specs, start a build, etc.)

\- Syntax Highlighting
.RS
git clone git://git.savannah.gnu.org/src-highlite.git

(Can be used as a cpp lib libsrchilite or as a terminal command)
.RE

\- Line Numbering

\- Buffered file i/o

\- Current buffer search

.SH DEPENDENCIES

\- ncurses (used during initial prototyping and to better understand the interface we need to the terminal.  Once this interface is understand, I'll remove this dependency.

.SH THEORY OF OPERATION
My notes and research product generated while planning and building E

Initial proof of concept and a lot of the base information is built upon
.UR https://viewsourcecode.org/snaptoken/kilo/index.html
this walkthrough
.UE .

.SS WORKFLOW

E is an entirely terminal based application used in a similar fashion to Vim except without all the bloat.
The basic workflow of the main application is:

.RS
1. Setup the terminal environment ("raw" mode)

2. Load/Parse file buffer

2. Loop on user input action

3. Restore the terminal to original environment

4. Exit
.RE

.SS LAYOUT
.EX
 ----------------------------------------------------------------------
| 1|                                                                   |
| 2|                                                                   |
| 3|                                                                   |
| 4|                                                                   |
| 5|                                                                   |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|~                                                                     |
|______________________________________________________________________|
| foo/bar.baz                                                1234/1234 |
 ----------------------------------------------------------------------
 ^^ ^
 || |
 || Current buffer name
 ||
 |Line Number
 |
 Gutter
.EE

.SH STRUCTURE

.RB e.h
.RS
Defines the E entrypoint along with global state management
.RE

.RB term.h
.RS
Contains all terminal-specific functions like setting up the TUI, writing to the terminal, etc.
.RE

.RB buffer.h
.RS
All functionality and state necessary to load a file into a memory buffer
.RE

.RB input.h
.RS
All input processing functions
.RE

.RB config.h
.RS
User defined configuration options
.RE
